services:
    notebooks:
        container_name: wine_analysis
        build: 
            context: ./notebooks 
        ports:
            - 8888:8888
        volumes:
            - ./notebooks:/home/notebooks
            - ./data:/home/data

